apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-canary
spec:
  replicas: ${CANARY_REPLICAS}
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: swapi123/train-schedule:latest
        ports:
        - containerPort: 8080
